# -*- coding: utf-8 -*-
"""Aula3sub.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XJnzyvGGOwZtFKcyqyfM51XlVqhWmF4z
"""

# ETE PORTO DIGITAL
# DISCIPLINA: LPC1
# PROFESSOR: CLOVES
# ESTUDANTES: RAVEL CEZAR

print ('Olá, ETE PORTO DIGITAL!')